<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Schedule</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; }
        .header h1 { margin: 0; font-size: 24px; }
        .header p { margin: 0; color: #555; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #888; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>{{ $date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Time</th>
                <th>Patient Name</th>
                @if(Auth::user()->role === 'admin')
                    <th>Doctor Name</th>
                @endif
                <th>Reason / Notes</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($appointments as $appointment)
                <tr>
                    <td>{{ \Carbon\Carbon::parse($appointment->appointment_date)->format('h:i A') }}</td>
                    <td>{{ $appointment->patient->name ?? 'N/A' }}</td>
                    @if(Auth::user()->role === 'admin')
                        <td>{{ $appointment->doctor->name ?? 'N/A' }}</td>
                    @endif
                    <td>{{ $appointment->reason ?? 'Not given' }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="{{ Auth::user()->role === 'admin' ? 4 : 3 }}" style="text-align: center;">No appointments scheduled for today.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by HealthCare Plus on {{ now() }}
    </div>
</body>
</html>